base_model = "minimax/MiniMax-M2.1"
reasoning_options = []
name = "MiniMax M2.1"
release_date = "2025-10-27"
knowledge = "2024-10"
open_weights = false

interleaved = true

[cost]
input = 0.3
output = 1.2
cache_read = 0.03
cache_write = 0.375
